version: '3.8'

services:
  app:
    image: node:24.3.0-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    working_dir: /workspace
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/nx_monorepo_db
      - REDIS_URL=redis://redis:6379
    networks:
      - dev-network

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nx_monorepo_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    networks:
      - dev-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - dev-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:

networks:
  dev-network:
    driver: bridge
